title: SkaterXL Modding Documentation
name: SkaterXL Modding Documentation
theme: jekyll-theme-slate
repository: Hofled/skaterxl-modding-documentation
defaults:
- scope:
    path: ""
  values:
    default_title_head: "false"
- scope:
    path: "assets/img"
  value:
    image: true