name: SkaterXL Modding Documentation
theme: jekyll-theme-slate
repository: https://github.com/Hofled/skaterxl-modding-documentation
defaults:
- scope:
    path: ""
  values:
    default_title_head: false